FIX: Fix missing intersection declaration
/run/build/BambuStudio/src/slic3r/GUI/GCodeRenderer/AdvancedRenderer.cpp:1006: error: ‘intersection’ was not declared in this scope; did you mean ‘Slic3r::line_alg::intersection’?
 1006 |                                 if (intersection({ p }, { convex_hull_2d }).empty() == false)