FIX: Fix missing BOOST_LOG_TRIVIAL declaration
/run/build/BambuStudio/src/libslic3r/GCode/ToolOrdering.cpp:1121:13: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
 1121 |             BOOST_LOG_TRIVIAL(error) << "Failed to build nozzle group result from filament nozzle map!";
      |             ^~~~~~~~~~~~~~~~~