FIX: Fix missing BOOST_LOG_TRIVIAL declaration
/run/build/BambuStudio/src/libslic3r/FilamentGroup.cpp:1213:17: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
 1213 |                 BOOST_LOG_TRIVIAL(info) << "Filament group" << count++ << ", score : " << cached_group.score << " , flush : " << cached_group.flush << " , time : " << cached_group.time << " , prefer : " << cached_group.prefer_level;
      |                 ^~~~~~~~~~~~~~~~~