FIX: Fix missing boost::lexical_cast declaration
/run/build/BambuStudio/src/slic3r/GUI/DeviceCore/DevMappingNozzle.cpp:42: error: ‘lexical_cast’ is not a member of ‘boost’
   42 |         float dia = boost::lexical_cast<float>(diameter);

/run/build/BambuStudio/src/slic3r/GUI/DeviceCore/DevUtilBackend.cpp: In static member function ‘static std::unordered_map<NozzleDef, int> Slic3r::DevUtilBackend::CollectNozzleInfo(Slic3r::MultiNozzleUtils::MultiNozzleGroupResult*, int)’:
/run/build/BambuStudio/src/slic3r/GUI/DeviceCore/DevUtilBackend.cpp:47: error: ‘lexical_cast’ is not a member of ‘boost’
   47 |             data.nozzle_diameter = boost::lexical_cast<float>(slicing_nozzle.diameter);