FIX: Fix missing wxBoxSizer declaration
/run/build/BambuStudio/src/slic3r/GUI/Widgets/LinkLabel.cpp: In constructor ‘LinkLabel::LinkLabel(wxWindow*, const wxString&, std::string, long int, wxSize)’:
/run/build/BambuStudio/src/slic3r/GUI/Widgets/LinkLabel.cpp:7:5: error: ‘wxBoxSizer’ was not declared in this scope; did you mean ‘wxSizer’?
    7 |     wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
      |     ^~~~~~~~~~
      |     wxSizer