FIX: Fix missing BOOST_LOG_TRIVIAL declaration
/run/build/BambuStudio/src/slic3r/Utils/FileTransferUtils.hpp:65:27: error: ‘info’ was not declared in this scope
   65 |         BOOST_LOG_TRIVIAL(info) << std::string("symbol not found: ") + name;
      |                           ^~~~
/run/build/BambuStudio/src/slic3r/Utils/FileTransferUtils.hpp:65:9: error: there are no arguments to ‘BOOST_LOG_TRIVIAL’ that depend on a template parameter, so a declaration of ‘BOOST_LOG_TRIVIAL’ must be available [-fpermissive]
   65 |         BOOST_LOG_TRIVIAL(info) << std::string("symbol not found: ") + name;
      |         ^~~~~~~~~~~~~~~~~