FIX: Fix missing std::ofstream/std::ifstream declaration
/run/build/BambuStudio/src/libslic3r/SVG.cpp: In function ‘void Slic3r::dumpExPolygonToJson(const ExPolygon&, const std::string&)’:
/run/build/BambuStudio/src/libslic3r/SVG.cpp:620:32: error: variable ‘std::ofstream file’ has initializer but incomplete type
  620 |     std::ofstream file(filePath);
      |                                ^
/run/build/BambuStudio/src/libslic3r/SVG.cpp:6:1: note: ‘std::ofstream’ is defined in header ‘<fstream>’; this is probably fixable by adding ‘#include <fstream>’
    5 | #include "nlohmann/json.hpp"
  +++ |+#include <fstream>
    6 |