FIX: Fix missing wxGridSizer declaration
/run/build/BambuStudio/src/slic3r/GUI/DragDropPanel.hpp:36:5: error: ‘wxGridSizer’ does not name a type; did you mean ‘wxSizer’?
   36 |     wxGridSizer *m_grid_item_sizer;
      |     ^~~~~~~~~~~
      |     wxSizer